import type { InformationToolDefinition } from "./types";
import { validateInformationToolDefinition } from "./validators";

export const STAGE3_TOOL_CATALOG_VERSION = "himam-stage3-tools-v1.0";

export const STAGE3_INFORMATION_TOOLS: InformationToolDefinition[] = [
  {
    toolId: "HIMAM_INSTITUTIONAL_ASSESSMENT_CORE",
    version: "1.0",
    nameKey: "tool.institutionalAssessment.core.name",
    descriptionKey: "tool.institutionalAssessment.core.description",
    category: "INSTITUTIONAL_ASSESSMENT",
    sourceType: "INSTITUTIONAL_ASSESSMENT",
    active: true,
    questions: [
      {
        questionId: "safety_current_performance",
        promptKey: "question.safetyCurrentPerformance",
        responseValueType: "RATING",
        required: true,
        conceptIds: ["SAFETY"],
        portfolioTargetIds: ["PF_CURRENT_PERFORMANCE"],
        operationalFunction: "ESTABLISH_CURRENT_PERFORMANCE",
        outputChannel: "EVIDENCE_RECORD",
        options: [
          { optionId: "independent", labelKey: "rating.independent", responseCode: "INDEPENDENT" },
          { optionId: "with_support", labelKey: "rating.withSupport", responseCode: "WITH_SUPPORT" },
          { optionId: "not_observed", labelKey: "rating.notObserved", responseCode: "NOT_OBSERVED" },
        ],
      },
    ],
  },
  {
    toolId: "HIMAM_LEARNER_VOICE_CORE",
    version: "1.0",
    nameKey: "tool.learnerVoice.core.name",
    descriptionKey: "tool.learnerVoice.core.description",
    category: "LEARNER_VOICE",
    sourceType: "LEARNER_VOICE",
    active: true,
    questions: [
      {
        questionId: "learner_preferred_activity",
        promptKey: "question.learnerPreferredActivity",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMM"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "learner_choice_expression",
        promptKey: "question.learnerChoiceExpression",
        responseValueType: "SINGLE_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM"],
        portfolioTargetIds: ["PF_SUPPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "speech", labelKey: "option.speech", responseCode: "CHOICE_BY_SPEECH" },
          { optionId: "aac", labelKey: "option.aac", responseCode: "CHOICE_BY_AAC" },
          { optionId: "gesture", labelKey: "option.gesture", responseCode: "CHOICE_BY_GESTURE" },
        ],
      },
    ],
  },
  {
    toolId: "HIMAM_FAMILY_VISION_CORE",
    version: "1.0",
    nameKey: "tool.familyVision.core.name",
    descriptionKey: "tool.familyVision.core.description",
    category: "FAMILY_VISION",
    sourceType: "FAMILY_VISION",
    active: true,
    questions: [
      {
        questionId: "family_top_priority",
        promptKey: "question.familyTopPriority",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_CARE", "COMMUNITY"],
        portfolioTargetIds: ["PF_PRIORITY"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "FAMILY_COMPASS_TALLY",
    version: "1.0",
    nameKey: "tool.familyCompassTally.name",
    descriptionKey: "tool.familyCompassTally.description",
    category: "FAMILY_VISION",
    sourceType: "FAMILY_VISION",
    active: true,
    questions: [
      {
        questionId: "family_compass_age_band",
        promptKey: "question.familyCompassAgeBand",
        responseValueType: "SINGLE_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY"],
        portfolioTargetIds: ["PF_CONTEXT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "under_12", labelKey: "option.under12", responseCode: "FAMILY_COMPASS_AGE_UNDER_12" },
          { optionId: "age_12_15", labelKey: "option.age12To15", responseCode: "FAMILY_COMPASS_AGE_12_15" },
          { optionId: "age_16_plus", labelKey: "option.age16Plus", responseCode: "FAMILY_COMPASS_AGE_16_PLUS" },
        ],
      },
      {
        questionId: "family_future_concerns",
        promptKey: "question.familyFutureConcerns",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "ACADEMIC", "SOCIAL", "COMMUNITY", "SAFETY", "COMM", "SELF_DET"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "daily_independence", labelKey: "option.dailyIndependence", responseCode: "FAMILY_CONCERN_DAILY_INDEPENDENCE", conceptIds: ["SELF_CARE"] },
          { optionId: "work_training", labelKey: "option.workTraining", responseCode: "FAMILY_CONCERN_WORK_TRAINING", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "relationships", labelKey: "option.relationships", responseCode: "FAMILY_CONCERN_RELATIONSHIPS", conceptIds: ["SOCIAL", "COMMUNITY"] },
          { optionId: "safety_protection", labelKey: "option.safetyProtection", responseCode: "FAMILY_CONCERN_SAFETY", conceptIds: ["SAFETY"] },
          { optionId: "communication_needs", labelKey: "option.communicationNeeds", responseCode: "FAMILY_CONCERN_COMMUNICATION", conceptIds: ["COMM"] },
          { optionId: "post_school_services", labelKey: "option.postSchoolServices", responseCode: "FAMILY_CONCERN_POST_SCHOOL_SERVICES", conceptIds: ["COMMUNITY", "SELF_DET"] },
          { optionId: "other", labelKey: "option.other", responseCode: "FAMILY_CONCERN_OTHER" },
        ],
      },
      {
        questionId: "family_hopes_next_years",
        promptKey: "question.familyHopesNextYears",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SELF_CARE", "ACADEMIC", "SOCIAL"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_PATHWAY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_observed_strengths",
        promptKey: "question.familyObservedStrengths",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "LEARNING_TECH", "SOCIAL", "ACADEMIC", "COMM", "COMMUNITY"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "learns_by_observation", labelKey: "option.learnsByObservation", responseCode: "FAMILY_STRENGTH_LEARNS_BY_OBSERVATION", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "likes_routine", labelKey: "option.likesRoutine", responseCode: "FAMILY_STRENGTH_LIKES_ROUTINE", conceptIds: ["SELF_DET"] },
          { optionId: "interacts_with_others", labelKey: "option.interactsWithOthers", responseCode: "FAMILY_STRENGTH_INTERACTS", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "hands_on_interest", labelKey: "option.handsOnInterest", responseCode: "FAMILY_STRENGTH_HANDS_ON", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "visual_instructions", labelKey: "option.visualInstructions", responseCode: "FAMILY_STRENGTH_VISUAL_INSTRUCTIONS", conceptIds: ["LEARNING_TECH", "COMM"] },
          { optionId: "clear_support", labelKey: "option.clearSupport", responseCode: "FAMILY_STRENGTH_CLEAR_SUPPORT", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "participation_desire", labelKey: "option.participationDesire", responseCode: "FAMILY_STRENGTH_PARTICIPATION", conceptIds: ["COMMUNITY", "SOCIAL"] },
          { optionId: "other", labelKey: "option.other", responseCode: "FAMILY_STRENGTH_OTHER" },
        ],
      },
      {
        questionId: "family_best_performance_contexts",
        promptKey: "question.familyBestPerformanceContexts",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SOCIAL", "ACADEMIC", "SELF_CARE"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "IDENTIFY_ENABLING_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_effective_supports",
        promptKey: "question.familyEffectiveSupports",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["COMM", "LEARNING_TECH", "SELF_DET", "SOCIAL", "HEALTH", "SELF_CARE"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "short_instructions", labelKey: "option.shortInstructions", responseCode: "FAMILY_SUPPORT_SHORT_INSTRUCTIONS", conceptIds: ["COMM"] },
          { optionId: "pictures_symbols", labelKey: "option.picturesSymbols", responseCode: "FAMILY_SUPPORT_PICTURES_SYMBOLS", conceptIds: ["COMM", "LEARNING_TECH"] },
          { optionId: "modeling", labelKey: "option.modeling", responseCode: "FAMILY_SUPPORT_MODELING", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "repetition_training", labelKey: "option.repetitionTraining", responseCode: "FAMILY_SUPPORT_REPETITION", conceptIds: ["ACADEMIC"] },
          { optionId: "reinforcement", labelKey: "option.reinforcement", responseCode: "FAMILY_SUPPORT_REINFORCEMENT", conceptIds: ["SELF_DET"] },
          { optionId: "familiar_person", labelKey: "option.familiarPerson", responseCode: "FAMILY_SUPPORT_FAMILIAR_PERSON", conceptIds: ["SOCIAL"] },
          { optionId: "task_steps", labelKey: "option.taskSteps", responseCode: "FAMILY_SUPPORT_TASK_STEPS", conceptIds: ["SELF_CARE", "ACADEMIC"] },
          { optionId: "more_time", labelKey: "option.moreTime", responseCode: "FAMILY_SUPPORT_MORE_TIME" },
          { optionId: "quiet_environment", labelKey: "option.quietEnvironment", responseCode: "FAMILY_SUPPORT_QUIET_ENVIRONMENT", conceptIds: ["HEALTH"] },
        ],
      },
      {
        questionId: "family_current_support_need",
        promptKey: "question.familyCurrentSupportNeed",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "COMM", "ACADEMIC", "COMMUNITY", "MOBILITY", "SOCIAL", "SELF_DET"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "self_care", labelKey: "option.selfCare", responseCode: "FAMILY_NEED_SELF_CARE", conceptIds: ["SELF_CARE"] },
          { optionId: "communication", labelKey: "option.communication", responseCode: "FAMILY_NEED_COMMUNICATION", conceptIds: ["COMM"] },
          { optionId: "time_routine", labelKey: "option.timeRoutine", responseCode: "FAMILY_NEED_TIME_ROUTINE", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "money", labelKey: "option.money", responseCode: "FAMILY_NEED_MONEY", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "community_mobility", labelKey: "option.communityMobility", responseCode: "FAMILY_NEED_COMMUNITY_MOBILITY", conceptIds: ["MOBILITY", "COMMUNITY", "SAFETY"] },
          { optionId: "work_readiness", labelKey: "option.workReadiness", responseCode: "FAMILY_NEED_WORK_READINESS", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "social_relationships", labelKey: "option.socialRelationships", responseCode: "FAMILY_NEED_SOCIAL_RELATIONSHIPS", conceptIds: ["SOCIAL"] },
          { optionId: "self_determination", labelKey: "option.selfDetermination", responseCode: "FAMILY_NEED_SELF_DETERMINATION", conceptIds: ["SELF_DET"] },
        ],
      },
      {
        questionId: "family_first_small_step",
        promptKey: "question.familyFirstSmallStep",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SELF_CARE", "COMM"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_ready_to_share",
        promptKey: "question.familyReadyToShare",
        responseValueType: "SINGLE_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "SOCIAL"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "yes", labelKey: "option.yes", responseCode: "FAMILY_READY_TO_SHARE_YES" },
          { optionId: "maybe", labelKey: "option.maybe", responseCode: "FAMILY_READY_TO_SHARE_MAYBE" },
          { optionId: "no", labelKey: "option.no", responseCode: "FAMILY_READY_TO_SHARE_NO" },
        ],
      },
    ],
  },
  {
    toolId: "FAMILY_VISION_SNAPSHOT",
    version: "1.0",
    nameKey: "tool.familyVisionSnapshot.name",
    descriptionKey: "tool.familyVisionSnapshot.description",
    category: "FAMILY_VISION",
    sourceType: "FAMILY_VISION",
    active: true,
    questions: [
      {
        questionId: "family_snapshot_future_1_3_years",
        promptKey: "question.familySnapshotFuture13Years",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SELF_CARE", "SOCIAL", "ACADEMIC"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_PATHWAY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_snapshot_child_matters_now",
        promptKey: "question.familySnapshotChildMattersNow",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "SOCIAL", "COMMUNITY"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_snapshot_family_priorities",
        promptKey: "question.familySnapshotFamilyPriorities",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["ACADEMIC", "SOCIAL", "HEALTH", "SAFETY", "SELF_CARE", "COMMUNITY", "COMM", "SELF_DET"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "learning", labelKey: "option.learning", responseCode: "FAMILY_SNAPSHOT_PRIORITY_LEARNING", conceptIds: ["ACADEMIC"] },
          { optionId: "participation", labelKey: "option.participation", responseCode: "FAMILY_SNAPSHOT_PRIORITY_PARTICIPATION", conceptIds: ["SOCIAL", "COMMUNITY"] },
          { optionId: "health", labelKey: "option.health", responseCode: "FAMILY_SNAPSHOT_PRIORITY_HEALTH", conceptIds: ["HEALTH"] },
          { optionId: "safety", labelKey: "option.safety", responseCode: "FAMILY_SNAPSHOT_PRIORITY_SAFETY", conceptIds: ["SAFETY"] },
          { optionId: "independence", labelKey: "option.independence", responseCode: "FAMILY_SNAPSHOT_PRIORITY_INDEPENDENCE", conceptIds: ["SELF_CARE", "SELF_DET"] },
          { optionId: "communication", labelKey: "option.communication", responseCode: "FAMILY_SNAPSHOT_PRIORITY_COMMUNICATION", conceptIds: ["COMM"] },
        ],
      },
      {
        questionId: "family_snapshot_more_possible",
        promptKey: "question.familySnapshotMorePossible",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "COMM", "SELF_CARE", "ACADEMIC"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_snapshot_effective_supports",
        promptKey: "question.familySnapshotEffectiveSupports",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["COMM", "LEARNING_TECH", "SELF_DET", "SOCIAL", "HEALTH", "ACADEMIC"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "visual_instructions", labelKey: "option.visualInstructions", responseCode: "FAMILY_SNAPSHOT_SUPPORT_VISUAL", conceptIds: ["COMM", "LEARNING_TECH"] },
          { optionId: "familiar_routine", labelKey: "option.familiarRoutine", responseCode: "FAMILY_SNAPSHOT_SUPPORT_ROUTINE", conceptIds: ["SELF_DET"] },
          { optionId: "more_time", labelKey: "option.moreTime", responseCode: "FAMILY_SNAPSHOT_SUPPORT_MORE_TIME" },
          { optionId: "nearby_person", labelKey: "option.nearbyPerson", responseCode: "FAMILY_SNAPSHOT_SUPPORT_NEARBY_PERSON", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "technology", labelKey: "option.technology", responseCode: "FAMILY_SNAPSHOT_SUPPORT_TECHNOLOGY", conceptIds: ["LEARNING_TECH"] },
          { optionId: "aac", labelKey: "option.aac", responseCode: "FAMILY_SNAPSHOT_SUPPORT_AAC", conceptIds: ["COMM", "LEARNING_TECH"] },
          { optionId: "demonstration", labelKey: "option.demonstration", responseCode: "FAMILY_SNAPSHOT_SUPPORT_DEMONSTRATION", conceptIds: ["ACADEMIC"] },
          { optionId: "choice_between_options", labelKey: "option.choiceBetweenOptions", responseCode: "FAMILY_SNAPSHOT_SUPPORT_CHOICE_OPTIONS", conceptIds: ["SELF_DET", "COMM"] },
        ],
      },
      {
        questionId: "family_snapshot_preserve_avoid_understand",
        promptKey: "question.familySnapshotPreserveAvoidUnderstand",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SAFETY", "HEALTH", "COMM", "SELF_DET", "SOCIAL"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "PRESERVE_FUNCTION",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "family_snapshot_transition_prompts_14_plus",
        promptKey: "question.familySnapshotTransitionPrompts14Plus",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "ACADEMIC", "SOCIAL"],
        portfolioTargetIds: ["PF_PATHWAY", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "PATHWAY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "FAMILY_VISION_PICTURE_CARDS",
    version: "1.0",
    nameKey: "tool.familyVisionPictureCards.name",
    descriptionKey: "tool.familyVisionPictureCards.description",
    category: "FAMILY_VISION",
    sourceType: "FAMILY_VISION",
    active: true,
    questions: [
      {
        questionId: "family_picture_card_scene",
        promptKey: "question.familyPictureCardScene",
        responseValueType: "SINGLE_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "SELF_CARE", "MOBILITY", "SOCIAL", "COMMUNITY", "HEALTH", "ACADEMIC", "LEARNING_TECH", "SAFETY"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "choosing_activities", labelKey: "option.choosingActivities", responseCode: "FAMILY_CARD_SCENE_CHOICE", conceptIds: ["SELF_DET"] },
          { optionId: "expressing_need", labelKey: "option.expressingNeed", responseCode: "FAMILY_CARD_SCENE_EXPRESSING_NEED", conceptIds: ["COMM"] },
          { optionId: "morning_self_care", labelKey: "option.morningSelfCare", responseCode: "FAMILY_CARD_SCENE_SELF_CARE", conceptIds: ["SELF_CARE"] },
          { optionId: "community_mobility", labelKey: "option.communityMobility", responseCode: "FAMILY_CARD_SCENE_MOBILITY", conceptIds: ["MOBILITY", "COMMUNITY", "SAFETY"] },
          { optionId: "peer_activity", labelKey: "option.peerActivity", responseCode: "FAMILY_CARD_SCENE_SOCIAL", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "community_resource", labelKey: "option.communityResource", responseCode: "FAMILY_CARD_SCENE_COMMUNITY", conceptIds: ["COMMUNITY"] },
          { optionId: "health_routine", labelKey: "option.healthRoutine", responseCode: "FAMILY_CARD_SCENE_HEALTH", conceptIds: ["HEALTH", "SELF_DET"] },
          { optionId: "functional_reading_numbers", labelKey: "option.functionalReadingNumbers", responseCode: "FAMILY_CARD_SCENE_ACADEMIC", conceptIds: ["ACADEMIC"] },
          { optionId: "phone_reminder", labelKey: "option.phoneReminder", responseCode: "FAMILY_CARD_SCENE_LEARNING_TECH", conceptIds: ["LEARNING_TECH", "ACADEMIC"] },
          { optionId: "safety_situation", labelKey: "option.safetySituation", responseCode: "FAMILY_CARD_SCENE_SAFETY", conceptIds: ["SAFETY"] },
        ],
      },
      {
        questionId: "family_picture_card_response",
        promptKey: "question.familyPictureCardResponse",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SAFETY", "HEALTH", "COMM"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "want_more", labelKey: "option.wantMore", responseCode: "FAMILY_CARD_WANT_MORE_OPPORTUNITIES", conceptIds: ["SELF_DET", "COMMUNITY"] },
          { optionId: "already_going_well", labelKey: "option.alreadyGoingWell", responseCode: "FAMILY_CARD_ALREADY_GOING_WELL", conceptIds: ["SELF_DET"] },
          { optionId: "important_support_needed", labelKey: "option.importantSupportNeeded", responseCode: "FAMILY_CARD_IMPORTANT_SUPPORT_NEEDED", conceptIds: ["COMM", "SELF_DET"] },
          { optionId: "want_to_explore", labelKey: "option.wantToExplore", responseCode: "FAMILY_CARD_WANT_TO_EXPLORE", conceptIds: ["SELF_DET", "COMMUNITY"] },
          { optionId: "preserve_works", labelKey: "option.preserveWorks", responseCode: "FAMILY_CARD_PRESERVE_WORKS", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "not_priority_now", labelKey: "option.notPriorityNow", responseCode: "FAMILY_CARD_NOT_PRIORITY_NOW" },
          { optionId: "not_enough_opportunity", labelKey: "option.notEnoughOpportunity", responseCode: "FAMILY_CARD_NOT_ENOUGH_OPPORTUNITY", conceptIds: ["SELF_DET", "COMMUNITY"] },
        ],
      },
      {
        questionId: "family_picture_card_what_matters",
        promptKey: "question.familyPictureCardWhatMatters",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "COMMUNITY", "SAFETY", "HEALTH"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_PATHWAY", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "participation", labelKey: "option.participation", responseCode: "FAMILY_CARD_MATTERS_PARTICIPATION", conceptIds: ["COMMUNITY", "SOCIAL"] },
          { optionId: "choice", labelKey: "option.choice", responseCode: "FAMILY_CARD_MATTERS_CHOICE", conceptIds: ["SELF_DET"] },
          { optionId: "communication", labelKey: "option.communication", responseCode: "FAMILY_CARD_MATTERS_COMMUNICATION", conceptIds: ["COMM"] },
          { optionId: "self_management", labelKey: "option.selfManagement", responseCode: "FAMILY_CARD_MATTERS_SELF_MANAGEMENT", conceptIds: ["SELF_DET", "SELF_CARE"] },
          { optionId: "safety", labelKey: "option.safety", responseCode: "FAMILY_CARD_MATTERS_SAFETY", conceptIds: ["SAFETY"] },
          { optionId: "confidence", labelKey: "option.confidence", responseCode: "FAMILY_CARD_MATTERS_CONFIDENCE", conceptIds: ["SELF_DET", "HEALTH"] },
          { optionId: "access", labelKey: "option.access", responseCode: "FAMILY_CARD_MATTERS_ACCESS", conceptIds: ["COMMUNITY", "MOBILITY"] },
          { optionId: "maintaining_ability", labelKey: "option.maintainingAbility", responseCode: "FAMILY_CARD_MATTERS_MAINTAINING_ABILITY", conceptIds: ["SELF_DET"] },
        ],
      },
      {
        questionId: "family_picture_card_existing_strengths",
        promptKey: "question.familyPictureCardExistingStrengths",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "SOCIAL", "LEARNING_TECH", "ACADEMIC"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "enjoys_this", labelKey: "option.enjoysThis", responseCode: "FAMILY_CARD_STRENGTH_ENJOYS_THIS", conceptIds: ["SELF_DET"] },
          { optionId: "notices_events", labelKey: "option.noticesEvents", responseCode: "FAMILY_CARD_STRENGTH_NOTICES_EVENTS", conceptIds: ["ACADEMIC"] },
          { optionId: "communicates_preferences", labelKey: "option.communicatesPreferences", responseCode: "FAMILY_CARD_STRENGTH_COMMUNICATES_PREFERENCES", conceptIds: ["COMM", "SELF_DET"] },
          { optionId: "remembers_routines", labelKey: "option.remembersRoutines", responseCode: "FAMILY_CARD_STRENGTH_REMEMBERS_ROUTINES", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "accepts_help", labelKey: "option.acceptsHelp", responseCode: "FAMILY_CARD_STRENGTH_ACCEPTS_HELP", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "uses_technology", labelKey: "option.usesTechnology", responseCode: "FAMILY_CARD_STRENGTH_USES_TECHNOLOGY", conceptIds: ["LEARNING_TECH"] },
          { optionId: "learns_repetition", labelKey: "option.learnsRepetition", responseCode: "FAMILY_CARD_STRENGTH_LEARNS_REPETITION", conceptIds: ["ACADEMIC"] },
          { optionId: "likes_others", labelKey: "option.likesOthers", responseCode: "FAMILY_CARD_STRENGTH_LIKES_OTHERS", conceptIds: ["SOCIAL"] },
        ],
      },
      {
        questionId: "family_picture_card_what_helps",
        promptKey: "question.familyPictureCardWhatHelps",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["COMM", "LEARNING_TECH", "SELF_DET", "SOCIAL", "ACADEMIC"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "visual_instructions", labelKey: "option.visualInstructions", responseCode: "FAMILY_CARD_HELP_VISUAL", conceptIds: ["COMM", "LEARNING_TECH"] },
          { optionId: "familiar_routine", labelKey: "option.familiarRoutine", responseCode: "FAMILY_CARD_HELP_ROUTINE", conceptIds: ["SELF_DET"] },
          { optionId: "more_time", labelKey: "option.moreTime", responseCode: "FAMILY_CARD_HELP_MORE_TIME" },
          { optionId: "nearby_person", labelKey: "option.nearbyPerson", responseCode: "FAMILY_CARD_HELP_NEARBY_PERSON", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "verbal_reminder", labelKey: "option.verbalReminder", responseCode: "FAMILY_CARD_HELP_VERBAL_REMINDER", conceptIds: ["COMM"] },
          { optionId: "technology", labelKey: "option.technology", responseCode: "FAMILY_CARD_HELP_TECHNOLOGY", conceptIds: ["LEARNING_TECH"] },
          { optionId: "aac", labelKey: "option.aac", responseCode: "FAMILY_CARD_HELP_AAC", conceptIds: ["COMM", "LEARNING_TECH"] },
          { optionId: "demonstration", labelKey: "option.demonstration", responseCode: "FAMILY_CARD_HELP_DEMONSTRATION", conceptIds: ["ACADEMIC"] },
          { optionId: "choice_between_options", labelKey: "option.choiceBetweenOptions", responseCode: "FAMILY_CARD_HELP_CHOICE_OPTIONS", conceptIds: ["SELF_DET", "COMM"] },
        ],
      },
    ],
  },
  {
    toolId: "HIMAM_INTEREST_SURVEY_CORE",
    version: "1.0",
    nameKey: "tool.interestSurvey.core.name",
    descriptionKey: "tool.interestSurvey.core.description",
    category: "INTEREST_SURVEY",
    sourceType: "INTEREST_SURVEY",
    active: true,
    questions: [
      {
        questionId: "interest_activity_cluster",
        promptKey: "question.interestActivityCluster",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "COMMUNITY"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT"],
        operationalFunction: "ACTIVITY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "technology", labelKey: "option.technology", responseCode: "INTEREST_TECHNOLOGY", conceptIds: ["LEARNING_TECH"] },
          { optionId: "movement", labelKey: "option.movement", responseCode: "INTEREST_MOVEMENT", conceptIds: ["MOBILITY"] },
          { optionId: "social_group", labelKey: "option.socialGroup", responseCode: "INTEREST_SOCIAL_GROUP", conceptIds: ["SOCIAL"] },
        ],
      },
    ],
  },
  {
    toolId: "HIMAM_INCLINATION_SURVEY_14_PLUS",
    version: "1.0",
    nameKey: "tool.inclinationSurvey14Plus.name",
    descriptionKey: "tool.inclinationSurvey14Plus.description",
    category: "INCLINATION_SURVEY",
    sourceType: "INCLINATION_SURVEY",
    active: true,
    questions: [
      {
        questionId: "future_pathway_interest",
        promptKey: "question.futurePathwayInterest",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "ACADEMIC", "LEARNING_TECH"],
        portfolioTargetIds: ["PF_PATHWAY", "PF_PRIORITY"],
        operationalFunction: "PATHWAY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "supported_work", labelKey: "option.supportedWork", responseCode: "PATHWAY_SUPPORTED_WORK" },
          { optionId: "community_participation", labelKey: "option.communityParticipation", responseCode: "PATHWAY_COMMUNITY_PARTICIPATION" },
          { optionId: "home_independence", labelKey: "option.homeIndependence", responseCode: "PATHWAY_HOME_INDEPENDENCE" },
        ],
      },
    ],
  },
  {
    toolId: "HIMAM_CAREER_INCLINATION_SCALE_TALLY",
    version: "1.0",
    nameKey: "tool.himamCareerInclinationScaleTally.name",
    descriptionKey: "tool.himamCareerInclinationScaleTally.description",
    category: "INCLINATION_SURVEY",
    sourceType: "INCLINATION_SURVEY",
    active: true,
    questions: [
      {
        questionId: "career_liked_clusters",
        promptKey: "question.careerLikedClusters",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "ACADEMIC", "COMMUNITY", "LEARNING_TECH", "SOCIAL"],
        portfolioTargetIds: ["PF_PATHWAY", "PF_PRIORITY", "PF_VOICE_PREFERENCE"],
        operationalFunction: "PATHWAY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "helping_others", labelKey: "option.helpingOthers", responseCode: "CAREER_LIKES_HELPING_OTHERS", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "hands_on_work", labelKey: "option.handsOnWork", responseCode: "CAREER_LIKES_HANDS_ON_WORK", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "organizing", labelKey: "option.organizing", responseCode: "CAREER_LIKES_ORGANIZING", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "technology_devices", labelKey: "option.technologyDevices", responseCode: "CAREER_LIKES_TECHNOLOGY_DEVICES", conceptIds: ["LEARNING_TECH", "ACADEMIC"] },
          { optionId: "hospitality_food", labelKey: "option.hospitalityFood", responseCode: "CAREER_LIKES_HOSPITALITY_FOOD", conceptIds: ["SELF_CARE", "COMMUNITY"] },
          { optionId: "sales_exchange", labelKey: "option.salesExchange", responseCode: "CAREER_LIKES_SALES_EXCHANGE", conceptIds: ["COMM", "COMMUNITY"] },
          { optionId: "agriculture_environment", labelKey: "option.agricultureEnvironment", responseCode: "CAREER_LIKES_AGRICULTURE_ENVIRONMENT", conceptIds: ["COMMUNITY", "HEALTH"] },
          { optionId: "art_design", labelKey: "option.artDesign", responseCode: "CAREER_LIKES_ART_DESIGN", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "mobility_field_tasks", labelKey: "option.mobilityFieldTasks", responseCode: "CAREER_LIKES_MOBILITY_FIELD_TASKS", conceptIds: ["MOBILITY", "COMMUNITY", "SAFETY"] },
          { optionId: "community_participation", labelKey: "option.communityParticipation", responseCode: "CAREER_LIKES_COMMUNITY_PARTICIPATION", conceptIds: ["COMMUNITY", "SOCIAL"] },
        ],
      },
      {
        questionId: "career_neutral_or_disliked_clusters",
        promptKey: "question.careerNeutralOrDislikedClusters",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "HEALTH", "SAFETY"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_BARRIER_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "helping_others", labelKey: "option.helpingOthers", responseCode: "CAREER_AVOIDS_HELPING_OTHERS", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "hands_on_work", labelKey: "option.handsOnWork", responseCode: "CAREER_AVOIDS_HANDS_ON_WORK", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "technology_devices", labelKey: "option.technologyDevices", responseCode: "CAREER_AVOIDS_TECHNOLOGY_DEVICES", conceptIds: ["LEARNING_TECH", "ACADEMIC"] },
          { optionId: "hospitality_food", labelKey: "option.hospitalityFood", responseCode: "CAREER_AVOIDS_HOSPITALITY_FOOD", conceptIds: ["SELF_CARE", "HEALTH"] },
          { optionId: "mobility_field_tasks", labelKey: "option.mobilityFieldTasks", responseCode: "CAREER_AVOIDS_MOBILITY_FIELD_TASKS", conceptIds: ["MOBILITY", "SAFETY"] },
        ],
      },
      {
        questionId: "career_support_conditions",
        promptKey: "question.careerSupportConditions",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["COMM", "SELF_DET", "SOCIAL", "SAFETY", "HEALTH"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "TRANSITION_AUTONOMY_CHECKLIST",
    version: "1.0",
    nameKey: "tool.transitionAutonomyChecklist.name",
    descriptionKey: "tool.transitionAutonomyChecklist.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "autonomy_readiness_summary",
        promptKey: "question.autonomyReadinessSummary",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "SELF_DET", "COMMUNITY", "SAFETY"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "daily_living_practice", labelKey: "option.dailyLivingPractice", responseCode: "AUTONOMY_DAILY_LIVING_PRACTICE", conceptIds: ["SELF_CARE"] },
          { optionId: "community_practice", labelKey: "option.communityPractice", responseCode: "AUTONOMY_COMMUNITY_PRACTICE", conceptIds: ["COMMUNITY"] },
          { optionId: "safety_practice", labelKey: "option.safetyPractice", responseCode: "AUTONOMY_SAFETY_PRACTICE", conceptIds: ["SAFETY"] },
          { optionId: "support_person_needed", labelKey: "option.supportPersonNeeded", responseCode: "AUTONOMY_SUPPORT_PERSON_NEEDED", conceptIds: ["SELF_DET", "COMM"] },
        ],
      },
    ],
  },
  {
    toolId: "TRANSITION_SKILLS_CHECKLIST",
    version: "1.0",
    nameKey: "tool.transitionSkillsChecklist.name",
    descriptionKey: "tool.transitionSkillsChecklist.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "transition_skill_coverage",
        promptKey: "question.transitionSkillCoverage",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["COMM", "SELF_DET", "SELF_CARE", "SAFETY", "HEALTH", "COMMUNITY"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "communication", labelKey: "option.communication", responseCode: "TSC_COMMUNICATION", conceptIds: ["COMM"] },
          { optionId: "self_advocacy", labelKey: "option.selfAdvocacy", responseCode: "TSC_SELF_ADVOCACY", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "daily_living", labelKey: "option.dailyLiving", responseCode: "TSC_DAILY_LIVING", conceptIds: ["SELF_CARE"] },
          { optionId: "safety", labelKey: "option.safety", responseCode: "TSC_SAFETY", conceptIds: ["SAFETY"] },
          { optionId: "health", labelKey: "option.health", responseCode: "TSC_HEALTH", conceptIds: ["HEALTH"] },
          { optionId: "community_resources", labelKey: "option.communityResources", responseCode: "TSC_COMMUNITY_RESOURCES", conceptIds: ["COMMUNITY"] },
        ],
      },
    ],
  },
  {
    toolId: "IEP_DISABILITY_AWARENESS_CHECKLIST",
    version: "1.0",
    nameKey: "tool.iepDisabilityAwarenessChecklist.name",
    descriptionKey: "tool.iepDisabilityAwarenessChecklist.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "iep_participation_awareness",
        promptKey: "question.iepParticipationAwareness",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "ACADEMIC", "COMMUNITY"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "knows_iep_meaning", labelKey: "option.knowsIepMeaning", responseCode: "IEP_AWARENESS_KNOWS_IEP", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "attended_iep_meeting", labelKey: "option.attendedIepMeeting", responseCode: "IEP_AWARENESS_ATTENDED_MEETING", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "knows_meeting_people", labelKey: "option.knowsMeetingPeople", responseCode: "IEP_AWARENESS_KNOWS_TEAM", conceptIds: ["COMM", "SOCIAL"] },
          { optionId: "knows_transition_age_14", labelKey: "option.knowsTransitionAge14", responseCode: "IEP_AWARENESS_TRANSITION_14_PLUS", conceptIds: ["SELF_DET", "COMMUNITY"] },
        ],
      },
      {
        questionId: "disability_and_support_awareness",
        promptKey: "question.disabilityAndSupportAwareness",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "HEALTH", "ACADEMIC"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "knows_disability", labelKey: "option.knowsDisability", responseCode: "IEP_AWARENESS_KNOWS_DISABILITY", conceptIds: ["SELF_DET", "HEALTH"] },
          { optionId: "knows_accommodations", labelKey: "option.knowsAccommodations", responseCode: "IEP_AWARENESS_KNOWS_ACCOMMODATIONS", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "knows_goals", labelKey: "option.knowsGoals", responseCode: "IEP_AWARENESS_KNOWS_GOALS", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "has_questions", labelKey: "option.hasQuestions", responseCode: "IEP_AWARENESS_HAS_QUESTIONS", conceptIds: ["COMM", "SELF_DET"] },
        ],
      },
    ],
  },
  {
    toolId: "FAMILY_TRANSITION_ASSESSMENT_INVOLVEMENT",
    version: "1.0",
    nameKey: "tool.familyTransitionAssessmentInvolvement.name",
    descriptionKey: "tool.familyTransitionAssessmentInvolvement.description",
    category: "FAMILY_VISION",
    sourceType: "FAMILY_VISION",
    active: true,
    questions: [
      {
        questionId: "family_transition_future_domains",
        promptKey: "question.familyTransitionFutureDomains",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SOCIAL", "COMM", "SAFETY"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "future_living_environment", labelKey: "option.futureLivingEnvironment", responseCode: "FAMILY_TRANSITION_FUTURE_LIVING", conceptIds: ["COMMUNITY", "SELF_CARE"] },
          { optionId: "future_employment_training", labelKey: "option.futureEmploymentTraining", responseCode: "FAMILY_TRANSITION_EMPLOYMENT_TRAINING", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "future_recreation_participation", labelKey: "option.futureRecreationParticipation", responseCode: "FAMILY_TRANSITION_RECREATION_PARTICIPATION", conceptIds: ["SOCIAL", "COMMUNITY"] },
          { optionId: "future_support_network", labelKey: "option.futureSupportNetwork", responseCode: "FAMILY_TRANSITION_SUPPORT_NETWORK", conceptIds: ["COMM", "SOCIAL"] },
          { optionId: "home_community_strengths", labelKey: "option.homeCommunityStrengths", responseCode: "FAMILY_TRANSITION_HOME_COMMUNITY_STRENGTHS", conceptIds: ["SELF_DET", "COMMUNITY"] },
        ],
      },
      {
        questionId: "family_assessment_participation_needs",
        promptKey: "question.familyAssessmentParticipationNeeds",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["COMM", "SOCIAL", "SELF_DET", "ACADEMIC"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "explain_assessment_purpose", labelKey: "option.explainAssessmentPurpose", responseCode: "FAMILY_TRANSITION_NEEDS_ASSESSMENT_PURPOSE", conceptIds: ["COMM"] },
          { optionId: "choose_family_input_tools", labelKey: "option.chooseFamilyInputTools", responseCode: "FAMILY_TRANSITION_CHOOSE_INPUT_TOOLS", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "interpret_results", labelKey: "option.interpretResults", responseCode: "FAMILY_TRANSITION_INTERPRET_RESULTS", conceptIds: ["COMM", "ACADEMIC"] },
          { optionId: "suggest_next_steps", labelKey: "option.suggestNextSteps", responseCode: "FAMILY_TRANSITION_SUGGEST_NEXT_STEPS", conceptIds: ["SELF_DET", "COMMUNITY"] },
          { optionId: "support_student_active_role", labelKey: "option.supportStudentActiveRole", responseCode: "FAMILY_TRANSITION_SUPPORT_STUDENT_ROLE", conceptIds: ["SELF_DET", "SOCIAL"] },
        ],
      },
      {
        questionId: "family_accessible_communication_note",
        promptKey: "question.familyAccessibleCommunicationNote",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["COMM", "SOCIAL", "SELF_DET"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "ADOLESCENT_AUTONOMY_CHECKLIST_REFERENCE",
    version: "1.0",
    nameKey: "tool.adolescentAutonomyChecklistReference.name",
    descriptionKey: "tool.adolescentAutonomyChecklistReference.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "autonomy_plan_to_start_domains",
        promptKey: "question.autonomyPlanToStartDomains",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "SAFETY", "HEALTH", "COMMUNITY", "MOBILITY", "ACADEMIC"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "kitchen_meals", labelKey: "option.kitchenMeals", responseCode: "AUTONOMY_PLAN_KITCHEN_MEALS", conceptIds: ["SELF_CARE", "SAFETY"] },
          { optionId: "laundry_clothing", labelKey: "option.laundryClothing", responseCode: "AUTONOMY_PLAN_LAUNDRY_CLOTHING", conceptIds: ["SELF_CARE"] },
          { optionId: "home_chores", labelKey: "option.homeChores", responseCode: "AUTONOMY_PLAN_HOME_CHORES", conceptIds: ["SELF_CARE"] },
          { optionId: "emergency_plan", labelKey: "option.emergencyPlan", responseCode: "AUTONOMY_PLAN_EMERGENCY", conceptIds: ["SAFETY", "COMM"] },
          { optionId: "health_management", labelKey: "option.healthManagement", responseCode: "AUTONOMY_PLAN_HEALTH", conceptIds: ["HEALTH", "SELF_DET"] },
          { optionId: "community_navigation", labelKey: "option.communityNavigation", responseCode: "AUTONOMY_PLAN_COMMUNITY_NAVIGATION", conceptIds: ["COMMUNITY", "MOBILITY", "SAFETY"] },
          { optionId: "money_consumer", labelKey: "option.moneyConsumer", responseCode: "AUTONOMY_PLAN_MONEY_CONSUMER", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "future_work_housing", labelKey: "option.futureWorkHousing", responseCode: "AUTONOMY_PLAN_WORK_HOUSING", conceptIds: ["ACADEMIC", "COMMUNITY", "SELF_DET"] },
        ],
      },
      {
        questionId: "autonomy_needs_practice_domains",
        promptKey: "question.autonomyNeedsPracticeDomains",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "SAFETY", "HEALTH", "COMMUNITY", "MOBILITY", "ACADEMIC"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_BARRIER_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "kitchen_meals", labelKey: "option.kitchenMeals", responseCode: "AUTONOMY_PRACTICE_KITCHEN_MEALS", conceptIds: ["SELF_CARE", "SAFETY"] },
          { optionId: "laundry_clothing", labelKey: "option.laundryClothing", responseCode: "AUTONOMY_PRACTICE_LAUNDRY_CLOTHING", conceptIds: ["SELF_CARE"] },
          { optionId: "home_chores", labelKey: "option.homeChores", responseCode: "AUTONOMY_PRACTICE_HOME_CHORES", conceptIds: ["SELF_CARE"] },
          { optionId: "emergency_plan", labelKey: "option.emergencyPlan", responseCode: "AUTONOMY_PRACTICE_EMERGENCY", conceptIds: ["SAFETY", "COMM"] },
          { optionId: "health_management", labelKey: "option.healthManagement", responseCode: "AUTONOMY_PRACTICE_HEALTH", conceptIds: ["HEALTH", "SELF_DET"] },
          { optionId: "community_navigation", labelKey: "option.communityNavigation", responseCode: "AUTONOMY_PRACTICE_COMMUNITY_NAVIGATION", conceptIds: ["COMMUNITY", "MOBILITY", "SAFETY"] },
          { optionId: "money_consumer", labelKey: "option.moneyConsumer", responseCode: "AUTONOMY_PRACTICE_MONEY_CONSUMER", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "future_work_housing", labelKey: "option.futureWorkHousing", responseCode: "AUTONOMY_PRACTICE_WORK_HOUSING", conceptIds: ["ACADEMIC", "COMMUNITY", "SELF_DET"] },
        ],
      },
      {
        questionId: "autonomy_can_do_domains",
        promptKey: "question.autonomyCanDoDomains",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "SAFETY", "HEALTH", "COMMUNITY", "MOBILITY", "ACADEMIC"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "kitchen_meals", labelKey: "option.kitchenMeals", responseCode: "AUTONOMY_CAN_KITCHEN_MEALS", conceptIds: ["SELF_CARE", "SAFETY"] },
          { optionId: "laundry_clothing", labelKey: "option.laundryClothing", responseCode: "AUTONOMY_CAN_LAUNDRY_CLOTHING", conceptIds: ["SELF_CARE"] },
          { optionId: "home_chores", labelKey: "option.homeChores", responseCode: "AUTONOMY_CAN_HOME_CHORES", conceptIds: ["SELF_CARE"] },
          { optionId: "emergency_plan", labelKey: "option.emergencyPlan", responseCode: "AUTONOMY_CAN_EMERGENCY", conceptIds: ["SAFETY", "COMM"] },
          { optionId: "health_management", labelKey: "option.healthManagement", responseCode: "AUTONOMY_CAN_HEALTH", conceptIds: ["HEALTH", "SELF_DET"] },
          { optionId: "community_navigation", labelKey: "option.communityNavigation", responseCode: "AUTONOMY_CAN_COMMUNITY_NAVIGATION", conceptIds: ["COMMUNITY", "MOBILITY", "SAFETY"] },
          { optionId: "money_consumer", labelKey: "option.moneyConsumer", responseCode: "AUTONOMY_CAN_MONEY_CONSUMER", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "future_work_housing", labelKey: "option.futureWorkHousing", responseCode: "AUTONOMY_CAN_WORK_HOUSING", conceptIds: ["ACADEMIC", "COMMUNITY", "SELF_DET"] },
        ],
      },
    ],
  },
  {
    toolId: "LIFE_SKILLS_INVENTORY_REFERENCE",
    version: "1.0",
    nameKey: "tool.lifeSkillsInventoryReference.name",
    descriptionKey: "tool.lifeSkillsInventoryReference.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "life_skills_gap_domains",
        promptKey: "question.lifeSkillsGapDomains",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_CARE", "HEALTH", "SAFETY", "COMMUNITY", "ACADEMIC", "SOCIAL"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_BARRIER_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "money_consumer", labelKey: "option.moneyConsumer", responseCode: "LSI_MONEY_CONSUMER", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "food_home", labelKey: "option.foodHome", responseCode: "LSI_FOOD_HOME", conceptIds: ["SELF_CARE", "SAFETY"] },
          { optionId: "health_hygiene", labelKey: "option.healthHygiene", responseCode: "LSI_HEALTH_HYGIENE", conceptIds: ["HEALTH", "SELF_CARE"] },
          { optionId: "transportation", labelKey: "option.transportation", responseCode: "LSI_TRANSPORTATION", conceptIds: ["MOBILITY", "SAFETY", "COMMUNITY"] },
          { optionId: "job_skills", labelKey: "option.jobSkills", responseCode: "LSI_JOB_SKILLS", conceptIds: ["ACADEMIC", "SELF_DET", "COMMUNITY"] },
          { optionId: "relationships", labelKey: "option.relationships", responseCode: "LSI_RELATIONSHIPS", conceptIds: ["SOCIAL", "COMM"] },
        ],
      },
      {
        questionId: "life_skill_observed_performance",
        promptKey: "question.lifeSkillObservedPerformance",
        responseValueType: "RATING",
        required: false,
        conceptIds: ["SELF_CARE"],
        portfolioTargetIds: ["PF_CURRENT_PERFORMANCE"],
        operationalFunction: "ESTABLISH_CURRENT_PERFORMANCE",
        outputChannel: "EVIDENCE_RECORD",
        options: [
          { optionId: "observed_independent", labelKey: "rating.observedIndependent", responseCode: "OBSERVED_INDEPENDENT" },
          { optionId: "observed_with_support", labelKey: "rating.observedWithSupport", responseCode: "OBSERVED_WITH_SUPPORT" },
          { optionId: "not_observed", labelKey: "rating.notObserved", responseCode: "NOT_OBSERVED" },
        ],
      },
    ],
  },
  {
    toolId: "EMPLOYABILITY_SKILLS_RUBRIC",
    version: "1.0",
    nameKey: "tool.employabilitySkillsRubric.name",
    descriptionKey: "tool.employabilitySkillsRubric.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "employability_observed_rating",
        promptKey: "question.employabilityObservedRating",
        responseValueType: "RATING",
        required: false,
        conceptIds: ["ACADEMIC", "SELF_DET", "SOCIAL", "COMMUNITY"],
        portfolioTargetIds: ["PF_CURRENT_PERFORMANCE"],
        operationalFunction: "ESTABLISH_CURRENT_PERFORMANCE",
        outputChannel: "EVIDENCE_RECORD",
        options: [
          { optionId: "usually_consistently", labelKey: "rating.usuallyConsistently", responseCode: "OBSERVED_INDEPENDENT" },
          { optionId: "inconsistently_with_support", labelKey: "rating.inconsistentlyWithSupport", responseCode: "OBSERVED_WITH_SUPPORT" },
          { optionId: "not_observed", labelKey: "rating.notObserved", responseCode: "NOT_OBSERVED" },
        ],
      },
      {
        questionId: "employability_support_context",
        promptKey: "question.employabilitySupportContext",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "ACADEMIC"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "COMMUNITY_WORKSITE_EVALUATION",
    version: "1.0",
    nameKey: "tool.communityWorksiteEvaluation.name",
    descriptionKey: "tool.communityWorksiteEvaluation.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "worksite_performance_rating",
        promptKey: "question.worksitePerformanceRating",
        responseValueType: "RATING",
        required: false,
        conceptIds: ["SAFETY", "SOCIAL", "COMM", "ACADEMIC", "COMMUNITY", "SELF_DET"],
        portfolioTargetIds: ["PF_CURRENT_PERFORMANCE"],
        operationalFunction: "ESTABLISH_CURRENT_PERFORMANCE",
        outputChannel: "EVIDENCE_RECORD",
        options: [
          { optionId: "observed_independent", labelKey: "rating.observedIndependent", responseCode: "OBSERVED_INDEPENDENT" },
          { optionId: "observed_with_support", labelKey: "rating.observedWithSupport", responseCode: "OBSERVED_WITH_SUPPORT" },
          { optionId: "not_observed", labelKey: "rating.notObserved", responseCode: "NOT_OBSERVED" },
        ],
      },
      {
        questionId: "worksite_context_notes",
        promptKey: "question.worksiteContextNotes",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["COMMUNITY", "SELF_DET", "SOCIAL"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "CAREER_PLANNING_TOOLKIT_REFERENCE",
    version: "1.0",
    nameKey: "tool.careerPlanningToolkitReference.name",
    descriptionKey: "tool.careerPlanningToolkitReference.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "career_planning_outputs",
        promptKey: "question.careerPlanningOutputs",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "ACADEMIC", "COMMUNITY", "LEARNING_TECH", "COMM"],
        portfolioTargetIds: ["PF_PATHWAY", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "PATHWAY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "self_determination", labelKey: "option.selfDetermination", responseCode: "CPT_SELF_DETERMINATION", conceptIds: ["SELF_DET"] },
          { optionId: "career_exploration", labelKey: "option.careerExploration", responseCode: "CPT_CAREER_EXPLORATION", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "work_based_learning", labelKey: "option.workBasedLearning", responseCode: "CPT_WORK_BASED_LEARNING", conceptIds: ["COMMUNITY", "ACADEMIC"] },
          { optionId: "goal_planning", labelKey: "option.goalPlanning", responseCode: "CPT_GOAL_PLANNING", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "technology_access", labelKey: "option.technologyAccess", responseCode: "CPT_TECHNOLOGY_ACCESS", conceptIds: ["LEARNING_TECH"] },
        ],
      },
    ],
  },
  {
    toolId: "CHARTING_LIFECOURSE_GUIDING_PRINCIPLES",
    version: "1.0",
    nameKey: "tool.chartingLifeCourseGuidingPrinciples.name",
    descriptionKey: "tool.chartingLifeCourseGuidingPrinciples.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "lifecourse_life_domain_focus",
        promptKey: "question.lifecourseLifeDomainFocus",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "SOCIAL", "HEALTH", "ACADEMIC", "SELF_CARE"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_PRIORITY", "PF_PATHWAY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "meaningful_day", labelKey: "option.meaningfulDay", responseCode: "LIFECOURSE_MEANINGFUL_DAY", conceptIds: ["ACADEMIC", "COMMUNITY", "SELF_DET"] },
          { optionId: "community_living", labelKey: "option.communityLiving", responseCode: "LIFECOURSE_COMMUNITY_LIVING", conceptIds: ["COMMUNITY", "SELF_CARE"] },
          { optionId: "social_spirituality", labelKey: "option.socialSpirituality", responseCode: "LIFECOURSE_SOCIAL_SPIRITUALITY", conceptIds: ["SOCIAL", "COMMUNITY"] },
          { optionId: "healthy_living", labelKey: "option.healthyLiving", responseCode: "LIFECOURSE_HEALTHY_LIVING", conceptIds: ["HEALTH", "SAFETY"] },
          { optionId: "citizenship_advocacy", labelKey: "option.citizenshipAdvocacy", responseCode: "LIFECOURSE_CITIZENSHIP_ADVOCACY", conceptIds: ["SELF_DET", "COMM"] },
        ],
      },
    ],
  },
  {
    toolId: "TRANSITION_TREASURE_MAP",
    version: "1.0",
    nameKey: "tool.transitionTreasureMap.name",
    descriptionKey: "tool.transitionTreasureMap.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "treasure_map_future_choices",
        promptKey: "question.treasureMapFutureChoices",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "ACADEMIC", "COMMUNITY", "MOBILITY", "SOCIAL"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_PATHWAY", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "PATHWAY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "future_learning", labelKey: "option.futureLearning", responseCode: "TREASURE_MAP_FUTURE_LEARNING", conceptIds: ["ACADEMIC", "SELF_DET"] },
          { optionId: "future_living", labelKey: "option.futureLiving", responseCode: "TREASURE_MAP_FUTURE_LIVING", conceptIds: ["COMMUNITY", "SELF_CARE"] },
          { optionId: "future_work", labelKey: "option.futureWork", responseCode: "TREASURE_MAP_FUTURE_WORK", conceptIds: ["ACADEMIC", "COMMUNITY"] },
          { optionId: "future_transportation", labelKey: "option.futureTransportation", responseCode: "TREASURE_MAP_FUTURE_TRANSPORTATION", conceptIds: ["MOBILITY", "SAFETY"] },
          { optionId: "future_community", labelKey: "option.futureCommunity", responseCode: "TREASURE_MAP_FUTURE_COMMUNITY", conceptIds: ["SOCIAL", "COMMUNITY"] },
        ],
      },
    ],
  },
  {
    toolId: "WHATS_IMPORTANT_TO_ME_CIRCLE",
    version: "1.0",
    nameKey: "tool.whatsImportantToMeCircle.name",
    descriptionKey: "tool.whatsImportantToMeCircle.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "important_life_priorities",
        promptKey: "question.importantLifePriorities",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "COMMUNITY", "HEALTH", "ACADEMIC"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_PRIORITY", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "relationships", labelKey: "option.relationships", responseCode: "IMPORTANT_RELATIONSHIPS", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "health_wellbeing", labelKey: "option.healthWellbeing", responseCode: "IMPORTANT_HEALTH_WELLBEING", conceptIds: ["HEALTH", "SAFETY"] },
          { optionId: "learning_growth", labelKey: "option.learningGrowth", responseCode: "IMPORTANT_LEARNING_GROWTH", conceptIds: ["ACADEMIC", "LEARNING_TECH"] },
          { optionId: "community_participation", labelKey: "option.communityParticipation", responseCode: "IMPORTANT_COMMUNITY_PARTICIPATION", conceptIds: ["COMMUNITY", "SOCIAL"] },
          { optionId: "choice_control", labelKey: "option.choiceControl", responseCode: "IMPORTANT_CHOICE_CONTROL", conceptIds: ["SELF_DET"] },
        ],
      },
      {
        questionId: "time_energy_alignment_note",
        promptKey: "question.timeEnergyAlignmentNote",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "HEALTH", "COMMUNITY"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_ENABLING_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "IEP_STUDENT_VISION_STATEMENT",
    version: "1.0",
    nameKey: "tool.iepStudentVisionStatement.name",
    descriptionKey: "tool.iepStudentVisionStatement.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "student_vision_future_statement",
        promptKey: "question.studentVisionFutureStatement",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "ACADEMIC", "SOCIAL", "COMM"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_PATHWAY", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "student_vision_strengths_supports",
        promptKey: "question.studentVisionStrengthsSupports",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "COMM", "COMMUNITY"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "LIFECOURSE_LIFE_TRAJECTORY",
    version: "1.0",
    nameKey: "tool.lifecourseLifeTrajectory.name",
    descriptionKey: "tool.lifecourseLifeTrajectory.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "trajectory_vision_want",
        promptKey: "question.trajectoryVisionWant",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "ACADEMIC", "SOCIAL"],
        portfolioTargetIds: ["PF_PATHWAY", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "trajectory_not_want",
        promptKey: "question.trajectoryNotWant",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "SAFETY", "HEALTH", "COMMUNITY"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_BARRIER_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "trajectory_helping_factors",
        promptKey: "question.trajectoryHelpingFactors",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["COMM", "SOCIAL", "SELF_DET", "COMMUNITY"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_PRIORITY"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "trajectory_preventing_factors",
        promptKey: "question.trajectoryPreventingFactors",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SAFETY", "HEALTH", "COMM", "COMMUNITY"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_BARRIER_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "LIFECOURSE_MY_PROFILE_PAGE",
    version: "1.0",
    nameKey: "tool.lifecourseMyProfilePage.name",
    descriptionKey: "tool.lifecourseMyProfilePage.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "profile_people_admire",
        promptKey: "question.profilePeopleAdmire",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "COMM", "ACADEMIC"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "profile_important_to_me",
        promptKey: "question.profileImportantToMe",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "COMMUNITY", "HEALTH"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "profile_best_support",
        promptKey: "question.profileBestSupport",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["COMM", "SOCIAL", "HEALTH", "SELF_CARE", "SELF_DET"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
  {
    toolId: "FUNCTIONAL_SKILLS_TRANSITION_ASSESSMENT",
    version: "1.0",
    nameKey: "tool.functionalSkillsTransitionAssessment.name",
    descriptionKey: "tool.functionalSkillsTransitionAssessment.description",
    category: "TRANSITION_SURVEY_CHECKLIST",
    sourceType: "TRANSITION_SURVEY_CHECKLIST",
    active: true,
    questions: [
      {
        questionId: "functional_transition_domain_coverage",
        promptKey: "question.functionalTransitionDomainCoverage",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SELF_DET", "COMM", "ACADEMIC", "SELF_CARE", "COMMUNITY", "SOCIAL", "SAFETY", "MOBILITY", "HEALTH"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT", "PF_SUPPORT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_PRIORITY",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "self_determination", labelKey: "option.selfDetermination", responseCode: "FSTA_SELF_DETERMINATION", conceptIds: ["SELF_DET", "COMM"] },
          { optionId: "communication_learning", labelKey: "option.communicationLearning", responseCode: "FSTA_COMMUNICATION_LEARNING", conceptIds: ["COMM", "ACADEMIC"] },
          { optionId: "daily_living", labelKey: "option.dailyLiving", responseCode: "FSTA_DAILY_LIVING", conceptIds: ["SELF_CARE", "HEALTH"] },
          { optionId: "community_mobility", labelKey: "option.communityMobility", responseCode: "FSTA_COMMUNITY_MOBILITY", conceptIds: ["COMMUNITY", "MOBILITY", "SAFETY"] },
          { optionId: "employment_readiness", labelKey: "option.employmentReadiness", responseCode: "FSTA_EMPLOYMENT_READINESS", conceptIds: ["ACADEMIC", "SELF_DET", "SOCIAL", "COMMUNITY"] },
          { optionId: "social_relationships", labelKey: "option.socialRelationships", responseCode: "FSTA_SOCIAL_RELATIONSHIPS", conceptIds: ["SOCIAL", "COMM"] },
        ],
      },
      {
        questionId: "functional_transition_observed_rating",
        promptKey: "question.functionalTransitionObservedRating",
        responseValueType: "RATING",
        required: false,
        conceptIds: ["SELF_DET"],
        portfolioTargetIds: ["PF_CURRENT_PERFORMANCE"],
        operationalFunction: "ESTABLISH_CURRENT_PERFORMANCE",
        outputChannel: "EVIDENCE_RECORD",
        options: [
          { optionId: "mastery", labelKey: "rating.mastery", responseCode: "OBSERVED_INDEPENDENT" },
          { optionId: "progressing", labelKey: "rating.progressing", responseCode: "OBSERVED_WITH_SUPPORT" },
          { optionId: "not_able_observed", labelKey: "rating.notAbleObserved", responseCode: "OBSERVED_NOT_ABLE" },
          { optionId: "dont_know", labelKey: "rating.dontKnow", responseCode: "NOT_OBSERVED" },
        ],
      },
    ],
  },
  {
    toolId: "SELF_DISCOVERY_ADVENTURE_TALLY",
    version: "1.0",
    nameKey: "tool.selfDiscoveryAdventureTally.name",
    descriptionKey: "tool.selfDiscoveryAdventureTally.description",
    category: "PERSON_CENTERED_PLANNING",
    sourceType: "PERSON_CENTERED_PLANNING",
    active: true,
    questions: [
      {
        questionId: "superpower_strength",
        promptKey: "question.superpowerStrength",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "ACADEMIC", "SOCIAL", "COMM"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "REPORT_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "free_time_interests",
        promptKey: "question.freeTimeInterests",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "SOCIAL", "COMMUNITY", "HEALTH"],
        portfolioTargetIds: ["PF_PRIORITY", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "ACTIVITY_INPUT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "learning_style",
        promptKey: "question.learningStyle",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["LEARNING_TECH", "ACADEMIC", "COMM", "SOCIAL", "SELF_DET"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_PRIORITY"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "videos", labelKey: "option.learningVideos", responseCode: "SELF_DISCOVERY_LEARNING_VIDEOS", conceptIds: ["LEARNING_TECH", "ACADEMIC"] },
          { optionId: "books", labelKey: "option.learningBooks", responseCode: "SELF_DISCOVERY_LEARNING_BOOKS", conceptIds: ["ACADEMIC"] },
          { optionId: "hands_on", labelKey: "option.learningHandsOn", responseCode: "SELF_DISCOVERY_LEARNING_HANDS_ON", conceptIds: ["SELF_DET", "ACADEMIC"] },
          { optionId: "discussion", labelKey: "option.learningDiscussion", responseCode: "SELF_DISCOVERY_LEARNING_DISCUSSION", conceptIds: ["COMM", "SOCIAL"] },
        ],
      },
      {
        questionId: "study_success_supports",
        promptKey: "question.studySuccessSupports",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["HEALTH", "COMM", "SOCIAL", "ACADEMIC"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "ideal_school_day",
        promptKey: "question.idealSchoolDay",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "ACADEMIC", "SOCIAL", "COMMUNITY", "HEALTH"],
        portfolioTargetIds: ["PF_CONTEXT", "PF_PRIORITY", "PF_REPORT"],
        operationalFunction: "IDENTIFY_ENABLING_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
      {
        questionId: "support_people",
        promptKey: "question.supportPeople",
        responseValueType: "MULTI_SELECT",
        required: false,
        conceptIds: ["SOCIAL", "COMM", "COMMUNITY", "SELF_DET"],
        portfolioTargetIds: ["PF_SUPPORT", "PF_CONTEXT", "PF_REPORT"],
        operationalFunction: "IDENTIFY_SUPPORT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
        options: [
          { optionId: "teachers", labelKey: "option.teachers", responseCode: "SELF_DISCOVERY_SUPPORT_TEACHERS", conceptIds: ["SOCIAL", "COMM"] },
          { optionId: "friends", labelKey: "option.friends", responseCode: "SELF_DISCOVERY_SUPPORT_FRIENDS", conceptIds: ["SOCIAL"] },
          { optionId: "family", labelKey: "option.family", responseCode: "SELF_DISCOVERY_SUPPORT_FAMILY", conceptIds: ["SOCIAL", "COMMUNITY"] },
          { optionId: "others", labelKey: "option.others", responseCode: "SELF_DISCOVERY_SUPPORT_OTHERS", conceptIds: ["COMMUNITY"] },
        ],
      },
      {
        questionId: "future_dream",
        promptKey: "question.futureDream",
        responseValueType: "TEXT",
        required: false,
        conceptIds: ["SELF_DET", "COMMUNITY", "ACADEMIC", "COMM"],
        portfolioTargetIds: ["PF_VOICE_PREFERENCE", "PF_PATHWAY", "PF_REPORT"],
        operationalFunction: "FUTURE_CONTEXT",
        outputChannel: "KNOWLEDGE_SUPPORT_ITEM",
      },
    ],
  },
];

export function getStage3InformationTool(toolId: string): InformationToolDefinition | null {
  return STAGE3_INFORMATION_TOOLS.find((tool) => tool.toolId === toolId) ?? null;
}

export function validateStage3ToolCatalog() {
  const issues = STAGE3_INFORMATION_TOOLS.flatMap((tool) =>
    validateInformationToolDefinition(tool).issues.map((issue) => ({
      toolId: tool.toolId,
      ...issue,
    })),
  );
  const toolIds = new Set(STAGE3_INFORMATION_TOOLS.map((tool) => tool.toolId));
  if (toolIds.size !== STAGE3_INFORMATION_TOOLS.length) {
    issues.push({
      toolId: "CATALOG",
      code: "DUPLICATE_TOOL_ID",
      message: "Stage 3 tool catalog must not contain duplicate tool IDs",
    });
  }
  return { ok: issues.length === 0, issues };
}
