/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdCoverageRouteImport } from './routes/students.$id.coverage'
import { Route as StudentsIdAssessmentRouteImport } from './routes/students.$id.assessment'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdCoverageRoute = StudentsIdCoverageRouteImport.update({
  id: '/students/$id/coverage',
  path: '/students/$id/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdAssessmentRoute = StudentsIdAssessmentRouteImport.update({
  id: '/students/$id/assessment',
  path: '/students/$id/assessment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students/new': typeof StudentsNewRoute
  '/students/$id/assessment': typeof StudentsIdAssessmentRoute
  '/students/$id/coverage': typeof StudentsIdCoverageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students/new': typeof StudentsNewRoute
  '/students/$id/assessment': typeof StudentsIdAssessmentRoute
  '/students/$id/coverage': typeof StudentsIdCoverageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students/new': typeof StudentsNewRoute
  '/students/$id/assessment': typeof StudentsIdAssessmentRoute
  '/students/$id/coverage': typeof StudentsIdCoverageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/students/new'
    | '/students/$id/assessment'
    | '/students/$id/coverage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/students/new'
    | '/students/$id/assessment'
    | '/students/$id/coverage'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/students/new'
    | '/students/$id/assessment'
    | '/students/$id/coverage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentsNewRoute: typeof StudentsNewRoute
  StudentsIdAssessmentRoute: typeof StudentsIdAssessmentRoute
  StudentsIdCoverageRoute: typeof StudentsIdCoverageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/coverage': {
      id: '/students/$id/coverage'
      path: '/students/$id/coverage'
      fullPath: '/students/$id/coverage'
      preLoaderRoute: typeof StudentsIdCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/assessment': {
      id: '/students/$id/assessment'
      path: '/students/$id/assessment'
      fullPath: '/students/$id/assessment'
      preLoaderRoute: typeof StudentsIdAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentsNewRoute: StudentsNewRoute,
  StudentsIdAssessmentRoute: StudentsIdAssessmentRoute,
  StudentsIdCoverageRoute: StudentsIdCoverageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
