/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdStudentVoiceRouteImport } from './routes/students.$id.student-voice'
import { Route as StudentsIdReportRouteImport } from './routes/students.$id.report'
import { Route as StudentsIdPlanRouteImport } from './routes/students.$id.plan'
import { Route as StudentsIdIepRouteImport } from './routes/students.$id.iep'
import { Route as StudentsIdFrameworkRouteImport } from './routes/students.$id.framework'
import { Route as StudentsIdFamilyRouteImport } from './routes/students.$id.family'
import { Route as StudentsIdCoverageRouteImport } from './routes/students.$id.coverage'
import { Route as StudentsIdAssessmentRouteImport } from './routes/students.$id.assessment'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdStudentVoiceRoute = StudentsIdStudentVoiceRouteImport.update({
  id: '/students/$id/student-voice',
  path: '/students/$id/student-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdReportRoute = StudentsIdReportRouteImport.update({
  id: '/students/$id/report',
  path: '/students/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdPlanRoute = StudentsIdPlanRouteImport.update({
  id: '/students/$id/plan',
  path: '/students/$id/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdIepRoute = StudentsIdIepRouteImport.update({
  id: '/students/$id/iep',
  path: '/students/$id/iep',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdFrameworkRoute = StudentsIdFrameworkRouteImport.update({
  id: '/students/$id/framework',
  path: '/students/$id/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdFamilyRoute = StudentsIdFamilyRouteImport.update({
  id: '/students/$id/family',
  path: '/students/$id/family',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdCoverageRoute = StudentsIdCoverageRouteImport.update({
  id: '/students/$id/coverage',
  path: '/students/$id/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdAssessmentRoute = StudentsIdAssessmentRouteImport.update({
  id: '/students/$id/assessment',
  path: '/students/$id/assessment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students/new': typeof StudentsNewRoute
  '/students/$id/assessment': typeof StudentsIdAssessmentRoute
  '/students/$id/coverage': typeof StudentsIdCoverageRoute
  '/students/$id/family': typeof StudentsIdFamilyRoute
  '/students/$id/framework': typeof StudentsIdFrameworkRoute
  '/students/$id/iep': typeof StudentsIdIepRoute
  '/students/$id/plan': typeof StudentsIdPlanRoute
  '/students/$id/report': typeof StudentsIdReportRoute
  '/students/$id/student-voice': typeof StudentsIdStudentVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students/new': typeof StudentsNewRoute
  '/students/$id/assessment': typeof StudentsIdAssessmentRoute
  '/students/$id/coverage': typeof StudentsIdCoverageRoute
  '/students/$id/family': typeof StudentsIdFamilyRoute
  '/students/$id/framework': typeof StudentsIdFrameworkRoute
  '/students/$id/iep': typeof StudentsIdIepRoute
  '/students/$id/plan': typeof StudentsIdPlanRoute
  '/students/$id/report': typeof StudentsIdReportRoute
  '/students/$id/student-voice': typeof StudentsIdStudentVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students/new': typeof StudentsNewRoute
  '/students/$id/assessment': typeof StudentsIdAssessmentRoute
  '/students/$id/coverage': typeof StudentsIdCoverageRoute
  '/students/$id/family': typeof StudentsIdFamilyRoute
  '/students/$id/framework': typeof StudentsIdFrameworkRoute
  '/students/$id/iep': typeof StudentsIdIepRoute
  '/students/$id/plan': typeof StudentsIdPlanRoute
  '/students/$id/report': typeof StudentsIdReportRoute
  '/students/$id/student-voice': typeof StudentsIdStudentVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/students/new'
    | '/students/$id/assessment'
    | '/students/$id/coverage'
    | '/students/$id/family'
    | '/students/$id/framework'
    | '/students/$id/iep'
    | '/students/$id/plan'
    | '/students/$id/report'
    | '/students/$id/student-voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/students/new'
    | '/students/$id/assessment'
    | '/students/$id/coverage'
    | '/students/$id/family'
    | '/students/$id/framework'
    | '/students/$id/iep'
    | '/students/$id/plan'
    | '/students/$id/report'
    | '/students/$id/student-voice'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/students/new'
    | '/students/$id/assessment'
    | '/students/$id/coverage'
    | '/students/$id/family'
    | '/students/$id/framework'
    | '/students/$id/iep'
    | '/students/$id/plan'
    | '/students/$id/report'
    | '/students/$id/student-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentsNewRoute: typeof StudentsNewRoute
  StudentsIdAssessmentRoute: typeof StudentsIdAssessmentRoute
  StudentsIdCoverageRoute: typeof StudentsIdCoverageRoute
  StudentsIdFamilyRoute: typeof StudentsIdFamilyRoute
  StudentsIdFrameworkRoute: typeof StudentsIdFrameworkRoute
  StudentsIdIepRoute: typeof StudentsIdIepRoute
  StudentsIdPlanRoute: typeof StudentsIdPlanRoute
  StudentsIdReportRoute: typeof StudentsIdReportRoute
  StudentsIdStudentVoiceRoute: typeof StudentsIdStudentVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/student-voice': {
      id: '/students/$id/student-voice'
      path: '/students/$id/student-voice'
      fullPath: '/students/$id/student-voice'
      preLoaderRoute: typeof StudentsIdStudentVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/report': {
      id: '/students/$id/report'
      path: '/students/$id/report'
      fullPath: '/students/$id/report'
      preLoaderRoute: typeof StudentsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/plan': {
      id: '/students/$id/plan'
      path: '/students/$id/plan'
      fullPath: '/students/$id/plan'
      preLoaderRoute: typeof StudentsIdPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/iep': {
      id: '/students/$id/iep'
      path: '/students/$id/iep'
      fullPath: '/students/$id/iep'
      preLoaderRoute: typeof StudentsIdIepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/framework': {
      id: '/students/$id/framework'
      path: '/students/$id/framework'
      fullPath: '/students/$id/framework'
      preLoaderRoute: typeof StudentsIdFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/family': {
      id: '/students/$id/family'
      path: '/students/$id/family'
      fullPath: '/students/$id/family'
      preLoaderRoute: typeof StudentsIdFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/coverage': {
      id: '/students/$id/coverage'
      path: '/students/$id/coverage'
      fullPath: '/students/$id/coverage'
      preLoaderRoute: typeof StudentsIdCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/assessment': {
      id: '/students/$id/assessment'
      path: '/students/$id/assessment'
      fullPath: '/students/$id/assessment'
      preLoaderRoute: typeof StudentsIdAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentsNewRoute: StudentsNewRoute,
  StudentsIdAssessmentRoute: StudentsIdAssessmentRoute,
  StudentsIdCoverageRoute: StudentsIdCoverageRoute,
  StudentsIdFamilyRoute: StudentsIdFamilyRoute,
  StudentsIdFrameworkRoute: StudentsIdFrameworkRoute,
  StudentsIdIepRoute: StudentsIdIepRoute,
  StudentsIdPlanRoute: StudentsIdPlanRoute,
  StudentsIdReportRoute: StudentsIdReportRoute,
  StudentsIdStudentVoiceRoute: StudentsIdStudentVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
